# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor, QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsDropShadowEffect


class Ui_img_view(object):
    def setupUi(self, img_view):
        img_view.setObjectName("img_view")
        img_view.resize(270, 220)
        img_view.setMinimumSize(QtCore.QSize(270, 220))
        img_view.setMaximumSize(QtCore.QSize(270, 220))
        img_view.setStyleSheet("*{\n"
                               "    font: normal 12px \"微软雅黑\";\n"
                               "    color:#FFF;\n"
                               "}\n"
                               "#img_view{\nborder-radius:3px;\n}\n"
                               "\n"
                               "#bottom_pannel{\n"
                               "\nborder-radius:3px;\n"
                               "    background-color:rgb(30, 35, 54)\n"
                               "}\n"
                               "\n"
                               "#byte_size_label,#type_label{\n"
                               "    padding:15px 10px 10px 10px;\n"
                               "    background-color:rgb(49, 49, 49,.45)\n"
                               "}\n"
                               "\n"
                               "#add_btn,#download_btn{\n"
                               "    border-radius: 3px;\n"
                               "    padding:5px 10px 5px 10px;\n"
                               "    min-width:35px;\n"
                               "    text-align:center;\n"
                               "    background:transparent;\n"
                               "}\n"
                               "\n"
                               "#add_btn:hover,#download_btn:hover{\n"
                               "    background-color:#2c626f;\n"
                               "}")
        self.img_label = QtWidgets.QLabel(img_view)
        self.img_label.setGeometry(QtCore.QRect(0, 0, 270, 180))
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap(":/images/preview.jpg"))
        self.img_label.setScaledContents(True)
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(img_view)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, -10, 272, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.top_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.top_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.top_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.top_horizontalLayout.setSpacing(0)
        self.top_horizontalLayout.setObjectName("top_horizontalLayout")
        self.type_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.type_label.setMinimumSize(QtCore.QSize(135, 40))
        self.type_label.setMaximumSize(QtCore.QSize(135, 40))
        self.type_label.setStyleSheet("")
        self.type_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.type_label.setObjectName("type_label")
        self.top_horizontalLayout.addWidget(self.type_label)
        self.byte_size_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.byte_size_label.setMinimumSize(QtCore.QSize(135, 40))
        self.byte_size_label.setMaximumSize(QtCore.QSize(135, 40))
        self.byte_size_label.setStyleSheet("")
        self.byte_size_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.byte_size_label.setObjectName("byte_size_label")
        self.top_horizontalLayout.addWidget(self.byte_size_label)
        self.bottom_pannel = QtWidgets.QWidget(img_view)
        self.bottom_pannel.setGeometry(QtCore.QRect(0, 180, 270, 40))
        self.bottom_pannel.setMinimumSize(QtCore.QSize(270, 40))
        self.bottom_pannel.setMaximumSize(QtCore.QSize(270, 40))
        self.bottom_pannel.setObjectName("bottom_pannel")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.bottom_pannel)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 271, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.bottom_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.bottom_horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.bottom_horizontalLayout.setSpacing(9)
        self.bottom_horizontalLayout.setObjectName("bottom_horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.add_btn.setObjectName("add_btn")
        self.bottom_horizontalLayout.addWidget(self.add_btn)
        self.size_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.size_label.setObjectName("size_label")
        self.bottom_horizontalLayout.addWidget(self.size_label)
        self.download_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.download_btn.setObjectName("download_btn")
        self.bottom_horizontalLayout.addWidget(self.download_btn)
        self.retranslateUi(img_view)
        self.set_shadow(img_view)
        QtCore.QMetaObject.connectSlotsByName(img_view)

    def retranslateUi(self, img_view):
        _translate = QtCore.QCoreApplication.translate
        img_view.setWindowTitle(_translate("img_view", "Frame"))
        self.type_label.setText(_translate("img_view", "1.2M"))
        self.byte_size_label.setText(_translate("img_view", "image/jpeg"))
        self.add_btn.setText(_translate("img_view", "加入轮换"))
        self.size_label.setText(_translate("img_view", "1200x1956"))
        self.download_btn.setText(_translate("img_view", "下载"))

    def set_shadow(self, img_view):
        shadowEffect = QGraphicsDropShadowEffect(img_view)
        # 设置阴影颜色, 透明度
        shadowEffect.setColor(QColor(0, 0, 0, 100))
        shadowEffect.setBlurRadius(15)
        shadowEffect.setOffset(5, 10)
        img_view.setGraphicsEffect(shadowEffect)

    def set_content(self, url, size, img_type, ratio):
        _translate = QtCore.QCoreApplication.translate
        image = QImage()
        image.loadFromData(requests.get(url).content)
        self.img_label.setPixmap(QPixmap(image))
        self.type_label.setText(_translate("img_view", '%.2fM' % (size / 1024 / 1024)))
        self.byte_size_label.setText(_translate("img_view", img_type))
        self.size_label.setText(_translate("img_view", ratio))


import resource_rc
