# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QListWidgetItem, QListView

from Image_View import Ui_img_view
from Ratio_Frame import Ui_Ratio_Frame


class Ui_MainWindow(object):
    def __init__(self):
        self.MainWindow = None
        self.Ui_Ratio_Frame = None

    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1454, 841)
        MainWindow.setStyleSheet("*{\n"
                                 "    font: normal 14px \"楷体\";\n"
                                 "}\n"
                                 "\n"
                                 "#centralwidget{\n"
                                 "    background-color: rgba(39,42,44,.45);\n"
                                 "    border-image: url(:/images/mian_bg.jpg);\n"
                                 "    \n"
                                 "}\n"
                                 "\n"
                                 "#left_widget{\n"
                                 "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(168, 168, 168,.15), stop:1 rgba(39,42,44,.15));\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "#my_bg_label,#more_info{\n"
                                 "    font: normal 16px \"楷体\";\n"
                                 "    color:#aaa;\n"
                                 "    padding:5px 20px;\n"
                                 "}\n"
                                 "\n"
                                 "#logo_label{\n"
                                 "    margin-left:12px;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar {\n"
                                 "    height:0px;\n"
                                 "    width:0px;\n"
                                 "}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_widget = QtWidgets.QWidget(self.centralwidget)
        self.left_widget.setEnabled(True)
        self.left_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.left_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.left_widget.setBaseSize(QtCore.QSize(43, 7))
        self.left_widget.setStyleSheet("QListWidget{\n"
                                       "    background: transparent;\n"
                                       "    outline:0px;\n"
                                       "    border:none;\n"
                                       "    font: normal 16px \"楷体\";\n"
                                       "    color:#c6c6c6;\n"
                                       "    padding:5px 85px 5px 45px;\n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "QListWidget::Item{\n"
                                       "    margin-top:10px;\n"
                                       "    background: transparent;\n"
                                       "}\n"
                                       "\n"
                                       "QListWidget::Item:hover,\n"
                                       "QListWidget::Item:selected {\n"
                                       "    color:#fff;\n"
                                       "}\n"
                                       "\n"
                                       "QListWidget::Item:selected {\n"
                                       "    border-bottom:2px solid qlineargradient(spread:reflect, x1:0, y1:0.016, x2:1, y2:1, stop:0.46438 rgba(0, 156, 218, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                       "}\n"
                                       "\n"
                                       "")
        self.left_widget.setObjectName("left_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.left_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 201, 841))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.logo_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMaximumSize(QtCore.QSize(150, 150))
        self.logo_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.logo_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.logo_label.setAutoFillBackground(False)
        self.logo_label.setInputMethodHints(QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhPreferNumbers)
        self.logo_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo_label.setText("")
        self.logo_label.setTextFormat(QtCore.Qt.AutoText)
        self.logo_label.setPixmap(QtGui.QPixmap(":/images/logo.svg"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.logo_label.setIndent(-1)
        self.logo_label.setOpenExternalLinks(False)
        self.logo_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_4.addWidget(self.logo_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.my_bg_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.my_bg_label.setStyleSheet("")
        self.my_bg_label.setObjectName("my_bg_label")
        self.verticalLayout.addWidget(self.my_bg_label)
        self.my_bg_list = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.my_bg_list.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.my_bg_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.my_bg_list.setObjectName("my_bg_list")
        item = QtWidgets.QListWidgetItem()
        self.my_bg_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.my_bg_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.my_bg_list.addItem(item)
        self.verticalLayout.addWidget(self.my_bg_list)
        self.more_info = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.more_info.setStyleSheet("")
        self.more_info.setObjectName("more_info")
        self.verticalLayout.addWidget(self.more_info)
        self.more_info_list = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.more_info_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.more_info_list.setObjectName("more_info_list")
        item = QtWidgets.QListWidgetItem()
        self.more_info_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.more_info_list.addItem(item)
        self.verticalLayout.addWidget(self.more_info_list)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.left_widget)
        self.contentWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.contentWidget.setStyleSheet("#contentWidget{\n"
                                         "    background-color: rgba(39,42,44,.25);\n"
                                         "}\n"
                                         "\n"
                                         "#page1_title,#page2_title,#page3_title,#page4_title,#page5_title{\n"
                                         "    padding:5px 0;\n"
                                         "    color:#fff;\n"
                                         "    font: normal 18px \"楷体\";\n"
                                         "}")
        self.contentWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.contentWidget.setLineWidth(0)
        self.contentWidget.setObjectName("contentWidget")
        self.online_page = QtWidgets.QWidget()
        self.online_page.setStyleSheet("background: transparent;")
        self.online_page.setObjectName("online_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.online_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.page1_title = QtWidgets.QLabel(self.online_page)
        self.page1_title.setStyleSheet("background-color: rgba(39,42,44,.35);")
        self.page1_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page1_title.setObjectName("page1_title")
        self.verticalLayout_2.addWidget(self.page1_title)
        self.search_bar = QtWidgets.QWidget(self.online_page)
        self.search_bar.setMinimumSize(QtCore.QSize(200, 60))
        self.search_bar.setStyleSheet(".QCheckBox{\n"
                                      "    border-radius: 3px;\n"
                                      "    padding:5px px 5px 0px;\n"
                                      "    /*width:auto;*/\n"
                                      "    min-width:35px;\n"
                                      "    max-width:60px;\n"
                                      "    text-align:center;\n"
                                      "    color: #aaa;\n"
                                      "    background-color:#353535;\n"
                                      "}\n"
                                      "\n"
                                      ".QCheckBox::checked{\n"
                                      "    color: #fff;\n"
                                      "    background-color:rgb(94, 94, 94);\n"
                                      "}\n"
                                      "\n"
                                      "#purity_sfw::checked{\n"
                                      "    color: #9f9;\n"
                                      "    background-color:#595;\n"
                                      "}\n"
                                      "\n"
                                      "#purity_sketchy::checked{\n"
                                      "    color: #ff9;\n"
                                      "    background-color:#995;\n"
                                      "}\n"
                                      "\n"
                                      "#purity_nsfw::checked{\n"
                                      "    color: #f99;\n"
                                      "    background-color:#955;\n"
                                      "}\n"
                                      "\n"
                                      ".QCheckBox::indicator{\n"
                                      "    width: 0px;\n"
                                      "}\n"
                                      "\n"
                                      "#ratio_btn{\n"
                                      "    border-radius: 3px;\n"
                                      "    padding:5px 10px 5px 10px;\n"
                                      "    min-width:35px;\n"
                                      "    text-align:center;\n"
                                      "    color: #fff;\n"
                                      "    background-color:#212224;\n"
                                      "    border:1px solid #353535;\n"
                                      "}\n"
                                      "\n"
                                      "#ratio_btn:hover {\n"
                                      "    background-color:#303030;\n"
                                      "}\n"
                                      "\n"
                                      "#search_btn{\n"
                                      "    border-radius: 3px;\n"
                                      "    padding:5px 10px 5px 10px;\n"
                                      "    min-width:35px;\n"
                                      "    text-align:center;\n"
                                      "    color: #fff;\n"
                                      "    background-color:#1f444e;\n"
                                      "    border:1px solid #353535;\n"
                                      "}\n"
                                      "\n"
                                      "#search_btn:hover{\n"
                                      "    background-color:#2c626f;\n"
                                      "}\n"
                                      "\n"
                                      ".QComboBox{\n"
                                      "    border-radius: 3px;\n"
                                      "    padding:5px 10px 5px 10px;\n"
                                      "    min-width:35px;\n"
                                      "    text-align:center;\n"
                                      "    color: #fff;\n"
                                      "    background-color:#212224;\n"
                                      "    border:1px solid #353535;\n"
                                      "}\n"
                                      "\n"
                                      ".QComboBox:hover {\n"
                                      "   background-color:#303030;\n"
                                      "}\n"
                                      "\n"
                                      "/* 下拉后，整个下拉窗体样式 */\n"
                                      "QComboBox QAbstractItemView {\n"
                                      "    outline: 0px solid gray;   /* 选定项的虚框 */\n"
                                      "    border: 1px solid #303030;   /* 整个下拉窗体的边框 */\n"
                                      "    color: #fff;\n"
                                      "    background-color: #303030;   /* 整个下拉窗体的背景色 */\n"
                                      "    selection-background-color: #696969;   /* 整个下拉窗体被选中项的背景色 */\n"
                                      "}\n"
                                      "\n"
                                      "/* 下拉后，整个下拉窗体每项的样式 */\n"
                                      "QComboBox QAbstractItemView::item {\n"
                                      "    color: #aaa;\n"
                                      "    background-color:#353535;\n"
                                      "}\n"
                                      "\n"
                                      "/* 下拉后，整个下拉窗体越过每项的样式 */\n"
                                      "QComboBox QAbstractItemView::item:hover {\n"
                                      "    color: #aaa;\n"
                                      "    background-color:#353535; /* 整个下拉窗体越过每项的背景色 */\n"
                                      "}\n"
                                      "\n"
                                      "/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
                                      "QComboBox QAbstractItemView::item:selected {\n"
                                      "    color: #aaa;\n"
                                      "    background-color:#565656;\n"
                                      "}\n"
                                      "\n"
                                      "QComboBox::down-arrow {\n"
                                      "    outline: 0px solid gray;   /* 选定项的虚框 */\n"
                                      "　　background: transparent; /* 下拉箭头的的背景色 */ \n"
                                      "　　padding: 0px 0px 0px 0px; /* 上内边距、右内边距、下内边距、左内边距 */\n"
                                      "}\n"
                                      "\n"
                                      "#search_bar{\n"
                                      "    align-items: center;\n"
                                      "    background-color: rgba(39,42,44,.35);\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.search_bar.setObjectName("search_bar")
        self.layoutWidget = QtWidgets.QWidget(self.search_bar)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1041, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cate_general = QtWidgets.QCheckBox(self.layoutWidget)
        self.cate_general.setMinimumSize(QtCore.QSize(45, 0))
        self.cate_general.setStyleSheet("padding-left:10px")
        self.cate_general.setObjectName("cate_general")
        self.horizontalLayout.addWidget(self.cate_general)
        self.cate_anime = QtWidgets.QCheckBox(self.layoutWidget)
        self.cate_anime.setStyleSheet("padding-left:10px")
        self.cate_anime.setObjectName("cate_anime")
        self.horizontalLayout.addWidget(self.cate_anime)
        self.cate_people = QtWidgets.QCheckBox(self.layoutWidget)
        self.cate_people.setMinimumSize(QtCore.QSize(45, 0))
        self.cate_people.setStyleSheet("padding-left:10px;\n"
                                       "")
        self.cate_people.setTristate(False)
        self.cate_people.setObjectName("cate_people")
        self.horizontalLayout.addWidget(self.cate_people)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.purity_sfw = QtWidgets.QCheckBox(self.layoutWidget)
        self.purity_sfw.setStyleSheet("padding-left:10px;")
        self.purity_sfw.setObjectName("purity_sfw")
        self.horizontalLayout_2.addWidget(self.purity_sfw)
        self.purity_sketchy = QtWidgets.QCheckBox(self.layoutWidget)
        self.purity_sketchy.setObjectName("purity_sketchy")
        self.horizontalLayout_2.addWidget(self.purity_sketchy)
        self.purity_nsfw = QtWidgets.QCheckBox(self.layoutWidget)
        self.purity_nsfw.setStyleSheet("padding-left:10px;")
        self.purity_nsfw.setObjectName("purity_nsfw")
        self.horizontalLayout_2.addWidget(self.purity_nsfw)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.ratio_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.ratio_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ratio_btn.setObjectName("ratio_btn")
        self.horizontalLayout_3.addWidget(self.ratio_btn)
        self.sorting_box = QtWidgets.QComboBox(self.layoutWidget)
        self.sorting_box.setMaximumSize(QtCore.QSize(90, 16777215))
        self.sorting_box.setObjectName("sorting_box")
        self.sorting_box.addItem("")
        self.sorting_box.addItem("")
        self.sorting_box.addItem("")
        self.sorting_box.addItem("")
        self.sorting_box.addItem("")
        self.sorting_box.addItem("")
        self.sorting_box.addItem("")
        self.horizontalLayout_3.addWidget(self.sorting_box)
        self.sort_range = QtWidgets.QComboBox(self.layoutWidget)
        self.sort_range.setMinimumSize(QtCore.QSize(57, 0))
        self.sort_range.setMaximumSize(QtCore.QSize(90, 16777215))
        self.sort_range.setObjectName("sort_range")
        self.sort_range.addItem("")
        self.sort_range.addItem("")
        self.sort_range.addItem("")
        self.sort_range.addItem("")
        self.sort_range.addItem("")
        self.sort_range.addItem("")
        self.sort_range.addItem("")
        self.space_hide(self.sort_range)
        self.horizontalLayout_3.addWidget(self.sort_range)
        self.search_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.search_input.setMinimumSize(QtCore.QSize(190, 0))
        self.search_input.setMaximumSize(QtCore.QSize(10, 16777215))
        self.search_input.setStyleSheet("color:#fff;\n"
                                        "flex-grow: 1;\n"
                                        "height: 2em;\n"
                                        "line-height: 2em;\n"
                                        "padding: 0 0.5em;\n"
                                        "background: #1b1b1b;\n"
                                        "border:1px solid #353535;\n"
                                        "border-radius: 3px;")
        self.search_input.setInputMask("")
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_3.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.search_btn.setMinimumSize(QtCore.QSize(57, 0))
        self.search_btn.setMaximumSize(QtCore.QSize(10, 16777215))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_3.addWidget(self.search_btn)
        self.verticalLayout_2.addWidget(self.search_bar)
        self.online_page_scroll = QtWidgets.QScrollArea(self.online_page)
        self.online_page_scroll.setStyleSheet("border:1px solid red;")
        self.online_page_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.online_page_scroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.online_page_scroll.setLineWidth(-1)
        self.online_page_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.online_page_scroll.setWidgetResizable(False)
        self.online_page_scroll.setObjectName("online_page_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1251, 753))
        self.scrollAreaWidgetContents.setAutoFillBackground(False)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.online_page_scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.online_page_scroll)
        self.contentWidget.addWidget(self.online_page)
        self.list_page = QtWidgets.QWidget()
        self.list_page.setStyleSheet("background: transparent;")
        self.list_page.setObjectName("list_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.list_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.page2_title = QtWidgets.QLabel(self.list_page)
        self.page2_title.setStyleSheet("background-color: rgba(39,42,44,.35);")
        self.page2_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page2_title.setObjectName("page2_title")
        self.verticalLayout_3.addWidget(self.page2_title)
        self.list_page_scroll = QtWidgets.QScrollArea(self.list_page)
        self.list_page_scroll.setStyleSheet("border:1px solid red;")
        self.list_page_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.list_page_scroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_page_scroll.setLineWidth(-1)
        self.list_page_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.list_page_scroll.setWidgetResizable(False)
        self.list_page_scroll.setObjectName("list_page_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1251, 811))
        self.scrollAreaWidgetContents_2.setAutoFillBackground(False)
        self.scrollAreaWidgetContents_2.setStyleSheet("")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.list_page_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.list_page_scroll)
        self.contentWidget.addWidget(self.list_page)
        self.download_page = QtWidgets.QWidget()
        self.download_page.setStyleSheet("background: transparent;")
        self.download_page.setObjectName("download_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.download_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.page3_title = QtWidgets.QLabel(self.download_page)
        self.page3_title.setStyleSheet("background-color: rgba(39,42,44,.35);")
        self.page3_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page3_title.setObjectName("page3_title")
        self.verticalLayout_4.addWidget(self.page3_title)
        self.download_page_scroll = QtWidgets.QScrollArea(self.download_page)
        self.download_page_scroll.setStyleSheet("border:1px solid red;")
        self.download_page_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.download_page_scroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.download_page_scroll.setLineWidth(-1)
        self.download_page_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.download_page_scroll.setWidgetResizable(False)
        self.download_page_scroll.setObjectName("download_page_scroll")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1251, 811))
        self.scrollAreaWidgetContents_3.setAutoFillBackground(False)
        self.scrollAreaWidgetContents_3.setStyleSheet("")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.download_page_scroll.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.download_page_scroll)
        self.contentWidget.addWidget(self.download_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.page4_title = QtWidgets.QLabel(self.setting_page)
        self.page4_title.setGeometry(QtCore.QRect(0, 0, 1254, 28))
        self.page4_title.setStyleSheet("background-color: rgba(39,42,44,.35);")
        self.page4_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page4_title.setObjectName("page4_title")
        self.contentWidget.addWidget(self.setting_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.page5_title = QtWidgets.QLabel(self.about_page)
        self.page5_title.setGeometry(QtCore.QRect(0, 0, 1254, 28))
        self.page5_title.setStyleSheet("background-color: rgba(39,42,44,.35);")
        self.page5_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page5_title.setObjectName("page5_title")
        self.contentWidget.addWidget(self.about_page)
        self.horizontalLayout_5.addWidget(self.contentWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.init_frame()
        self.contentWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.my_bg_label.setText(_translate("MainWindow", "我的壁纸"))
        __sortingEnabled = self.my_bg_list.isSortingEnabled()
        self.my_bg_list.setSortingEnabled(False)
        item = self.my_bg_list.item(0)
        item.setText(_translate("MainWindow", "在线壁纸"))
        item = self.my_bg_list.item(1)
        item.setText(_translate("MainWindow", "轮换列表"))
        item = self.my_bg_list.item(2)
        item.setText(_translate("MainWindow", "下载中心"))
        self.my_bg_list.setSortingEnabled(__sortingEnabled)
        self.more_info.setText(_translate("MainWindow", "更多"))
        __sortingEnabled = self.more_info_list.isSortingEnabled()
        self.more_info_list.setSortingEnabled(False)
        item = self.more_info_list.item(0)
        item.setText(_translate("MainWindow", "设置"))
        item = self.more_info_list.item(1)
        item.setText(_translate("MainWindow", "关于"))
        self.more_info_list.setSortingEnabled(__sortingEnabled)
        self.page1_title.setText(_translate("MainWindow", "在线壁纸"))
        self.cate_general.setText(_translate("MainWindow", "普通"))
        self.cate_anime.setText(_translate("MainWindow", "动漫"))
        self.cate_people.setText(_translate("MainWindow", "人物"))
        self.purity_sfw.setText(_translate("MainWindow", " SFW"))
        self.purity_sketchy.setText(_translate("MainWindow", "Sketchy"))
        self.purity_nsfw.setText(_translate("MainWindow", "NSFW"))
        self.ratio_btn.setText(_translate("MainWindow", "比例 ▼"))
        self.sorting_box.setItemText(0, _translate("MainWindow", "热度"))
        self.sorting_box.setItemText(1, _translate("MainWindow", "排行榜"))
        self.sorting_box.setItemText(2, _translate("MainWindow", "随机"))
        self.sorting_box.setItemText(3, _translate("MainWindow", "日期"))
        self.sorting_box.setItemText(4, _translate("MainWindow", "收藏数"))
        self.sorting_box.setItemText(5, _translate("MainWindow", "相关性"))
        self.sorting_box.setItemText(6, _translate("MainWindow", "视图"))
        self.sort_range.setItemText(0, _translate("MainWindow", "一天"))
        self.sort_range.setItemText(1, _translate("MainWindow", "三天"))
        self.sort_range.setItemText(2, _translate("MainWindow", "一周"))
        self.sort_range.setItemText(3, _translate("MainWindow", "一个月"))
        self.sort_range.setItemText(4, _translate("MainWindow", "三个月"))
        self.sort_range.setItemText(5, _translate("MainWindow", "六个月"))
        self.sort_range.setItemText(6, _translate("MainWindow", "一年"))
        self.search_btn.setText(_translate("MainWindow", "搜索"))
        self.page2_title.setText(_translate("MainWindow", "轮换列表"))
        self.page3_title.setText(_translate("MainWindow", "下载中心"))
        self.page4_title.setText(_translate("MainWindow", "轮换列表"))
        self.page5_title.setText(_translate("MainWindow", "轮换列表"))

    # ===============================================================
    def init_frame(self):
        if not self.Ui_Ratio_Frame:
            self.Ui_Ratio_Frame = QtWidgets.QWidget(self.MainWindow)
            Ui_Ratio_Frame_ui = Ui_Ratio_Frame()
            Ui_Ratio_Frame_ui.setupUi(self.Ui_Ratio_Frame)
            self.Ui_Ratio_Frame.setGeometry(688, 70, 319, 191)
            self.Ui_Ratio_Frame.hide()
        self.add_image()

    def bind_event(self):
        """绑定事件"""
        self.my_bg_list.setCurrentRow(0)
        self.my_bg_list.itemClicked.connect(self.my_bg_list_change)
        self.more_info_list.itemClicked.connect(self.more_info_list_change)
        self.sorting_box.currentIndexChanged.connect(self.sorting_box_changed)
        self.sort_range.currentIndexChanged.connect(self.sorting_range_changed)
        self.ratio_btn.clicked.connect(self.ratio_btn_click)

    def my_bg_list_change(self):
        """侧边栏壁纸监听"""
        self.more_info_list.clearSelection()
        self.contentWidget.setCurrentIndex(self.my_bg_list.currentRow())

    def more_info_list_change(self):
        """侧边栏更多监听"""
        self.my_bg_list.clearSelection()
        self.contentWidget.setCurrentIndex(3 + self.more_info_list.currentRow())

    def sorting_box_changed(self):
        """排序方式改变"""
        if self.sorting_box.currentIndex() == 1:
            self.space_show(self.sort_range)
        else:
            self.space_hide(self.sort_range)

    def sorting_range_changed(self):
        """排序方式改变"""
        print(self.sort_range.currentIndex())

    def ratio_btn_click(self):
        """点击比例按钮"""
        if self.Ui_Ratio_Frame.isHidden():
            self.ratio_btn.setText("比例 ▲")
            self.ratio_btn.setStyleSheet("background-color:#303030;")
            self.Ui_Ratio_Frame.show()
        else:
            self.Ui_Ratio_Frame.hide()
            self.ratio_btn.setText("比例 ▼")
            self.ratio_btn.setStyleSheet("background-color:#212224;")

    def add_image(self):
        images_list_widget = QtWidgets.QListWidget(self.online_page_scroll)
        images_list_widget.resize(1250,840)
        images_list_widget.setResizeMode(QListView.Adjust)
        images_list_widget.setViewMode(QListView.IconMode)
        images_list_widget.setMovement(QListView.Static)
        images_list_widget.setSpacing(8)


        for i in range(20):
            widget_item = QListWidgetItem()
            widget_item.setSizeHint(QSize(270, 220))
            img_view = Ui_img_view()
            q_widget = QtWidgets.QWidget()
            img_view.setupUi(q_widget)
            images_list_widget.addItem(widget_item)
            images_list_widget.setItemWidget(widget_item, q_widget)
        images_list_widget.show()

    def space_hide(self, obj):
        """占位隐藏"""
        op = QtWidgets.QGraphicsOpacityEffect()
        # 设置透明度的值，0.0到1.0，最小值0是透明，1是不透明
        op.setOpacity(0)
        obj.setGraphicsEffect(op)
        obj.setEnabled(False)

    def space_show(self, obj):
        """占位隐藏取消"""
        op = QtWidgets.QGraphicsOpacityEffect()
        # 设置透明度的值，0.0到1.0，最小值0是透明，1是不透明
        op.setOpacity(1)
        obj.setGraphicsEffect(op)
        obj.setEnabled(True)


import resource_rc
