# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ratio_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ratio_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("ratio_frame")
        Frame.resize(319, 191)
        Frame.setStyleSheet("#ratio_frame{border-radius: 3px;border:1px solid #353535;"
                            "border-top:none;}\n"
                            "*{\n"
                            "    font: normal 14px \"微软雅黑\";\n"
                            "    color: #fff;\n"
                            "    background-color:#303030;\n"
                            "}\n"
                            "\n"
                            ".QLabel{\n"
                            "    min-width:35px;\n"
                            "    text-align:center;\n"
                            "}\n"
                            "\n"
                            ".QCheckBox{\n"
                            "    border-radius: 3px;\n"
                            "    padding:5px 5px 5px 15px;\n"
                            "    /*width:auto;*/\n"
                            "    min-width:35px;\n"
                            "    text-align:center;\n"
                            "    color: #aaa;\n"
                            "    background-color:#353535;\n"
                            "}\n"
                            "\n"
                            ".QCheckBox::checked{\n"
                            "    color: #fff;\n"
                            "    background-color:rgb(94, 94, 94);\n"
                            "}\n"
                            ".QCheckBox::indicator{\n"
                            "    width: 0px;\n"
                            "}")
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_wide = QtWidgets.QLabel(Frame)
        self.label_wide.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_wide.setObjectName("label_wide")
        self.gridLayout.addWidget(self.label_wide, 0, 0, 1, 1)
        self.label_ultrawide = QtWidgets.QLabel(Frame)
        self.label_ultrawide.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_ultrawide.setObjectName("label_ultrawide")
        self.gridLayout.addWidget(self.label_ultrawide, 0, 1, 1, 1)
        self.label_portrait = QtWidgets.QLabel(Frame)
        self.label_portrait.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_portrait.setObjectName("label_portrait")
        self.gridLayout.addWidget(self.label_portrait, 0, 2, 1, 1)
        self.label_square = QtWidgets.QLabel(Frame)
        self.label_square.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_square.setObjectName("label_square")
        self.gridLayout.addWidget(self.label_square, 0, 3, 1, 1)
        self.ratio_16x9 = QtWidgets.QCheckBox(Frame)
        self.ratio_16x9.setObjectName("ratio_16x9")
        self.gridLayout.addWidget(self.ratio_16x9, 1, 0, 1, 1)
        self.ratio_21x9 = QtWidgets.QCheckBox(Frame)
        self.ratio_21x9.setObjectName("ratio_21x9")
        self.gridLayout.addWidget(self.ratio_21x9, 1, 1, 1, 1)
        self.ratio_9x16 = QtWidgets.QCheckBox(Frame)
        self.ratio_9x16.setObjectName("ratio_9x16")
        self.gridLayout.addWidget(self.ratio_9x16, 1, 2, 1, 1)
        self.ratio_1x1 = QtWidgets.QCheckBox(Frame)
        self.ratio_1x1.setObjectName("ratio_1x1")
        self.gridLayout.addWidget(self.ratio_1x1, 1, 3, 1, 1)
        self.ratio_16x10 = QtWidgets.QCheckBox(Frame)
        self.ratio_16x10.setObjectName("ratio_16x10")
        self.gridLayout.addWidget(self.ratio_16x10, 2, 0, 1, 1)
        self.ratio_32x9 = QtWidgets.QCheckBox(Frame)
        self.ratio_32x9.setObjectName("ratio_32x9")
        self.gridLayout.addWidget(self.ratio_32x9, 2, 1, 1, 1)
        self.ratio_10x16 = QtWidgets.QCheckBox(Frame)
        self.ratio_10x16.setObjectName("ratio_10x16")
        self.gridLayout.addWidget(self.ratio_10x16, 2, 2, 1, 1)
        self.ratio_3x2 = QtWidgets.QCheckBox(Frame)
        self.ratio_3x2.setObjectName("ratio_3x2")
        self.gridLayout.addWidget(self.ratio_3x2, 2, 3, 1, 1)
        self.ratio_48x9 = QtWidgets.QCheckBox(Frame)
        self.ratio_48x9.setObjectName("ratio_48x9")
        self.gridLayout.addWidget(self.ratio_48x9, 3, 1, 1, 1)
        self.ratio_9x18 = QtWidgets.QCheckBox(Frame)
        self.ratio_9x18.setObjectName("ratio_9x18")
        self.gridLayout.addWidget(self.ratio_9x18, 3, 2, 1, 1)
        self.ratio_4x3 = QtWidgets.QCheckBox(Frame)
        self.ratio_4x3.setObjectName("ratio_4x3")
        self.gridLayout.addWidget(self.ratio_4x3, 3, 3, 1, 1)
        self.ratio_5x4 = QtWidgets.QCheckBox(Frame)
        self.ratio_5x4.setObjectName("ratio_5x4")
        self.gridLayout.addWidget(self.ratio_5x4, 4, 3, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_wide.setText(_translate("Frame", "Wide"))
        self.label_ultrawide.setText(_translate("Frame", "Ultrawide"))
        self.label_portrait.setText(_translate("Frame", "Portrait"))
        self.label_square.setText(_translate("Frame", "Square"))
        self.ratio_16x9.setText(_translate("Frame", "16x9"))
        self.ratio_21x9.setText(_translate("Frame", "21x9"))
        self.ratio_9x16.setText(_translate("Frame", "9x16"))
        self.ratio_1x1.setText(_translate("Frame", "1x1"))
        self.ratio_16x10.setText(_translate("Frame", "16x10"))
        self.ratio_32x9.setText(_translate("Frame", "32x9"))
        self.ratio_10x16.setText(_translate("Frame", "10x16"))
        self.ratio_3x2.setText(_translate("Frame", "3x2"))
        self.ratio_48x9.setText(_translate("Frame", "48x9"))
        self.ratio_9x18.setText(_translate("Frame", "9x18"))
        self.ratio_4x3.setText(_translate("Frame", "4x3"))
        self.ratio_5x4.setText(_translate("Frame", "5x4"))
